<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-04-04T20:28:38+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'fr_FR',
    'version_installed' => '8.3.2',
    'version_db_installed' => '20180122213656',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1522866506,
    ],
];
